# Users
USERNAME_MAX_LENGTH = 150
PASSWORD_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
UNALLOWED_USERNAME = 'me'

# Tags
TAG_NAME_MAX_LENGTH = 200
TAG_DEFAULT_COLOR = '#000000'
TAG_SLUG_MAX_LENGTH = 200

# Ingredients
INGREDIENT_NAME_MAX_LENGTH = 150
UNIT_NAME_MAX_LENGTH = 200

# Recipes
RECIPE_NAME_MAX_LENGTH = 200
IMAGE_UPLOAD_PATH = 'recipe_images/'

# Pagination
PAGE_SIZE = 6
MAX_PAGE_SIZE = 1000
